server:
  port: 8093
spring:
  application:
    name: aws-rds-mysql-demo
    url: https://aws.amazon.com/
    description: This is ${spring.application.name},Power by Spring on JDK21
  datasource:
    username: user_xxx
    password: password_xxx
    url: jdbc:aws-wrapper:mysql://multi-az-cluster.cluster-xxxx.us-east-1.rds.amazonaws.com:3306/think_db
    driver-class-name: software.amazon.jdbc.Driver
    hikari:
      pool-name: ${spring.application.name}
      connection-timeout: 3000
      maximum-pool-size: 32
      minimum-idle: 4
      # 8 min
      idle-timeout: 480000
      # 1 hour
      max-lifetime: 600000
      # 1 min
      keepalive-time: 60000
      auto-commit: true
      read-only: false
      exception-override-class-name: software.amazon.jdbc.util.HikariCPSQLException
      data-source-properties:
        # https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/UsingTheJdbcDriver.md#list-of-available-plugins
        wrapperPlugins: auroraConnectionTracker,failover,efm2,logQuery,dev
        # https://github.com/aws/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/DatabaseDialects.md
        wrapperDialect: rds-multi-az-mysql-cluster
        wrapperLoggerLevel: INFO
logging:
  level:
    software:
      amazon:
        jdbc: TRACE
# -----Mybatis----------------------------------------------------------------------------------------------------------
mybatis:
  config-location: true
  mapper-locations: classpath:mybatis-mapper/*.xml
  type-aliases-package: com.example.awsrdsmysqldemo.beans
  configuration:
    cache-enabled: true
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
